pull_request_rules:

  # ===============================================================================
  # AUTOMATIC MERGE (APPROVALS)
  # ===============================================================================

  - name: Automatic Merge ⬇️ on Approval ✔
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - check-success='test (1.22.x, ubuntu-latest)'
      - check-success='test (1.23.x, ubuntu-latest)'
      - check-success='test (1.24.x, ubuntu-latest)'
      - check-success='Analyze (go)'
      - -title~=(?i)wip
      - label!=work-in-progress
      - -draft
    actions:
      merge:
        method: merge

  # ===============================================================================
  # BRANCHES
  # ===============================================================================

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
