pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependabot Minor Version Pull Requests
    conditions:
      - -draft
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='test (1.22.x, ubuntu-latest)'
      - check-success='test (1.23.x, ubuntu-latest)'
      - check-success='test (1.24.x, ubuntu-latest)'
      - check-success='Analyze (go)'
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot pull request
      merge:
        method: merge
  - name: Alert on major version detection
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='test (1.22.x, ubuntu-latest)'
      - check-success='test (1.23.x, ubuntu-latest)'
      - check-success='test (1.24.x, ubuntu-latest)'
      - check-success='Analyze (go)'
      - -title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      comment:
        message: "⚠️ @mrz1836: this is a major version bump and requires your attention"

  # ===============================================================================
  # AUTOMATIC MERGE (APPROVALS)
  # ===============================================================================

  - name: Automatic Merge ⬇️ on Approval ✔
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - check-success='test (1.22.x, ubuntu-latest)'
      - check-success='test (1.23.x, ubuntu-latest)'
      - check-success='test (1.24.x, ubuntu-latest)'
      - check-success='Analyze (go)'
      - -title~=(?i)wip
      - label!=work-in-progress
      - -draft
    actions:
      merge:
        method: merge

  # ===============================================================================
  # BRANCHES
  # ===============================================================================

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
