name: Label PRs by Branch Prefix

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels based on branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const labels = [];
            const labelMap = [
              { regex: /^feat\//i, label: 'feature' },
              { regex: /^(bug)?fix\//i, label: 'bug-P3' },
              { regex: /^docs\//i, label: 'documentation' },
              { regex: /^chore\//i, label: 'update' },
              { regex: /^test\//i, label: 'test' },
              { regex: /^refactor\//i, label: 'refactor' },
              { regex: /^hotfix\//i, label: 'hot-fix' },
              { regex: /^proto(type)?\//i, label: 'prototype' },
              { regex: /^idea\//i, label: 'idea' },
              { regex: /^question\//i, label: 'question' },
            ];
            for (const { regex, label } of labelMap) {
              if (regex.test(branch)) {
                labels.push(label);
              }
            }
            if (labels.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels,
              });
            }

